-- Direct OTP fallback: stores short-lived hashed codes for the rare case
-- where Supabase Auth's built-in send-email hook is not configured or is
-- temporarily rejected by the mail provider. Codes are generated by an Edge
-- Function, sent via Brevo, and verified server-side. Only the service role
-- can read or write this table; it is never exposed to anonymous users.
create table if not exists public.direct_otp_codes (
  id uuid default gen_random_uuid() primary key,
  email text not null,
  action text not null,
  code_hash text not null,
  attempts int not null default 0,
  used boolean not null default false,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_direct_otp_codes_lookup
  on public.direct_otp_codes (email, created_at desc);

-- Only service_role (Edge Functions) may touch this table.
alter table public.direct_otp_codes enable row level security;

create policy if not exists "service_role_only"
  on public.direct_otp_codes
  as restrictive
  for all
  to service_role
  using (true)
  with check (true);
